### ISSUE TITLE
make the scripts optional as part of an extra

### ISSUE THREAD

**Issue by DetachHead** [njzjz/nodejs-wheel#23]
i'm considering switching to this project from [nodejs-bin](https://pypi.org/project/nodejs-bin/). it makes the `node`, `npm` and `npx` scripts optional and only installs them if you install the `cmd` extra:

```bash
pip install 'nodejs-bin[cmd]'
```

that's useful in my case because i only need to call node programmatically and not via the command line, and i'd prefer users of my package to not unknowingly have a node binary added to their path.

**Comment by njzjz** [comment]
We may have two options to do it (like https://github.com/scikit-build/cmake-python-distributions/issues/80#issuecomment-502787361). One is
- nodejs-wheel[cmd]
- nodejs-wheel

Another one is
- nodejs-wheel
- nodejs-wheel-binaries
(nodejs-wheel is based on nodejs-wheel-binaries)

I prefer the second one, as it has no breaking change to `nodejs-wheel`.
