### ISSUE TITLE
Add Windows arm64 binaries

### ISSUE THREAD

**Issue by aivarannamaa** [njzjz/nodejs-wheel#87]
Since version 20 (or at least 20.18.1) Node.js publishes binaries for Windows Arm64 architecture. Could you please upload these as well?

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the build_wheels job in the GitHub Actions workflow to include Windows ARM64 architecture. This will allow building and uploading Node.js binaries for Windows Arm64, addressing the issue mentioned in the criteria.

You can review changes in this commit: https://github.com/mnmnk43434/njzjz-nodejs-wheel-87/commit/30e5fc140ca72618245c46ca7dd2819f9ab2918f.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by njzjz** [comment]
I will try it after https://github.com/nodejs/build/issues/3963 is fixed with the GitHub Actions. Note that in this repository, binaries are rebuilt instead of just reuploading the official binaries.
